set -o vi

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

HISTSIZE=16384
HISTFILESIZE=16384

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize cdspell extglob globstar

RED='\[\e[1;31m\]'
GREEN='\[\e[1;32m\]'
YELLOW='\[\e[1;33m\]'
BLUE='\[\e[1;34m\]'
MAGENTA='\[\e[1;35m\]'
CYAN='\[\e[1;36m\]'
WHITE='\[\e[1;37m\]'
RESET='\[\e[0m\]'

git_branch() {
  if git rev-parse --is-inside-work-tree &> /dev/null; then
    echo ">$(__git_ps1 "[%s]")"
  fi
}

PS1="${BLUE}\u@\h:${MAGENTA}"'${PWD}'"${BLUE}"'$(git_branch)'"${RESET}\$ "

# colored GCC warnings and errors
export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some ls aliases
alias la='ls -lAhF --group-directories-first --color=auto'
alias ls='ls -CF --group-directories-first --color=auto'

# editor
alias vim='nvim'
export EDITOR=nvim
export MANPAGER="nvim +Man!"

# general stuff
alias cdp='cd ~-'
alias cl='clear -x'
alias so='source'
alias cdb='cd ..'
alias battery='echo "$(\cat /sys/class/power_supply/BAT1/capacity)%"'

# git
source /usr/share/bash-completion/completions/git
alias gsw='git switch'
alias gst='git status'
alias gaa='git add .'
alias gcm='git commit'
alias glg='git log --all --decorate --oneline --graph --stat'
alias gdf='git diff'
alias gps='git push'
alias gfc='git fetch'
alias gme='git merge'
alias gbr='git branch'

__git_complete gsw _git_switch
__git_complete gst _git_status
__git_complete gaa _git_add
__git_complete gcm _git_commit
__git_complete glg _git_log
__git_complete gdf _git_diff
__git_complete gps _git_push
__git_complete gfc _git_fetch
__git_complete gme _git_merge
__git_complete gbr _git_branch

# functions
function n {
  for ((i = 1; i <= $1; i++)); do
    eval "$2"
  done
}

function cd {
    builtin cd "$@" && ls
}

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
  bind 'TAB:menu-complete'
fi
